### ISSUE TITLE
issue w/ letsencrypt.sh

### ISSUE THREAD

**Issue by mghenderson** [spreedbox/spreedbox#11]
So I'm using the wiki page [Generate a Let's Encrypt certificate](https://github.com/spreedbox/spreedbox/wiki/Generate-a-Let%27s-Encrypt-certificate), but have run into issues.

``` shell
spreedbox@spreedbox:~$ sudo letsencrypt.sh --cron
# INFO: Using main config file /etc/letsencrypt.sh/config.sh
# INFO: Using additional config file /etc/letsencrypt.sh/conf.d/empty.sh
Processing phoenixgrey.duckdns.org
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting challenge for phoenixgrey.duckdns.org...
spreedbox@spreedbox:~$
```

As you can see, it exits w/o any output or information, so I'm guessing the challenge failed.  I instead turned to [cerbot](https://certbot.eff.org/) to generate the certificates, which seem successful (as shown by the following code block).  I ended up having to stop `nginx` for the duration of the `certbot` run so it could use port 80.

``` shell
IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at
   /etc/letsencrypt/live/phoenixgrey.duckdns.org/fullchain.pem. Your
   cert will expire on 2016-08-23. To obtain a new version of the
   certificate in the future, simply run Certbot again.
```

So, now I seemingly have the certificates, but apparently I don't have them in the proper location, or something else isn't configured correctly.  If we can get the `letsencrypt.sh` to work correctly, fantastic, I'd be happy to use that.  If I need to use `certbot`, then any help with getting the certs in place & configured would be fantastic.  Either way, some time spent updating the wiki page would be helpful for everyone.

**Comment by fancycode** [comment]
letsencrypt has slightly changed the response to the challenge which wasn't supported by `letsencrypt.sh` properly (see https://github.com/lukas2511/letsencrypt.sh/pull/202).

We will release an updated package for `letsencrypt.sh` shortly.

**Comment by mghenderson** [comment]
@fancycode I'm guessing you've released that updated package.  Do I need to pull it directly from the git repo, or is there a better way?

**Comment by fancycode** [comment]
If you are already on the `titan` firmware release, you should be able to update the package as described in https://github.com/spreedbox/spreedbox/wiki/Software-Update. If not, you can either flash the latest firmware image as described in https://github.com/spreedbox/spreedbox/wiki/Firmware-Upgrade.

Another option would be to activate my PPA from https://launchpad.net/~fancycode/+archive/ubuntu/letsencrypt, which always provides the latest version.
