### ISSUE TITLE
Spreedbox not working!

### ISSUE THREAD

**Issue by rferreiroa** [spreedbox/spreedbox#18]
Hi, 
we bought spreedbox 2 months ago without succeed.
We tried to connect in two differents networks and nohting.

One time, we could see in a web browser with an local IP (192.168.1.xxx) the start panel but when we tried to register username and password seems to be registered or something.

The problem is that we cannot access via SSH and cannot access via web. Any solution?

Kind regards,

**Comment by fancycode** [comment]
The Spreedbox is requesting an IP address from the DHCP server, so you could check that for the IP address that was assigned and that can be used to connect to the Spreedbox.

Further information about setting up a Spreedbox can be found in the wiki: https://github.com/spreedbox/spreedbox/wiki/Getting-Started

**Comment by rferreiroa** [comment]
The problem is that i can see via web and via ssh but in both cases, dont work. I cannot register a new user via web and via SSH with username spreedbox -> Access denied

**Comment by leonklingele** [comment]
Have you tried to set up a new user using a different browser / an incognito (private) browser session?

SSH is disabled by default and can be enabled once you the initial user is created.

**Comment by rferreiroa** [comment]
Fortunately, the problem is that someone created the first user. All is ok and ssh activated in setup  configuration now.

Thx!!!
