### ISSUE TITLE
Custom port not honoured after login

### ISSUE THREAD

**Issue by jasperla** [spreedbox/spreedbox#2]
We've configured the spreedbox to run on 8080 as per [Run webserver on custom ports](https://github.com/spreedbox/spreedbox/wiki/Run-webserver-on-custom-ports) (while still on https). It works fine when navigating to https://spreedbox.address:8080/ logging in works, but the next page it tries to load uses port 443 and not 8080. Manually adding `:8080` to the URL works. Is there another setting that needs to be updated perhaps?

**Comment by fancycode** [comment]
This will be fixed in the upcoming package spreedbox-owncloud 0.0.27.

As a workaround you can edit `/etc/nginx/spreedbox.d/spreedbox-owncloud.conf` (as user `root` or through `sudo`) and change the line

```
fastcgi_param HTTP_X_FORWARDED_HOST $host;
```

to

```
fastcgi_param HTTP_X_FORWARDED_HOST $http_host;
```

Reload nginx afterwards:

```
$ sudo service nginx reload
```

**Comment by jasperla** [comment]
Thanks, confirmed it resolves our issue.

Is there an ETA for that update?

**Comment by fancycode** [comment]
The package should be in the repository later today so you can update using `apt-get update && apt-get upgrade`. We currently don't have an ETA for a complete firmware image containing the updated package.
