### ISSUE TITLE
GPG Error invalid signature - Struktur AG Server on apt-get update

### ISSUE THREAD

**Issue by Niederfuchs** [spreedbox/spreedbox#20]
Today, when I tried to update my Spreedbox using the usual routine. Spreedbox gave me an GPG Error:

W: GPG error: http://deb.devices.struktur.de trusty InRelease: The following signatures were invalid: KEYEXPIRED 1510756064

**Comment by fancycode** [comment]
Unfortunately we missed publishing an updated key with extended validity in time before the pre-installed key expired.

While the message mentions `GPG error` it actually is a just warning for `apt`. Once we publish the updated key, you will automatically get the new package.

**Comment by fancycode** [comment]
As a workaround you can manually import the updated key using this command (on your Spreedbox):
```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C575C565
```

**Comment by fancycode** [comment]
Published an entry to the wiki in case somebody else has a similar problem:
https://github.com/spreedbox/spreedbox/wiki/Software-Update#gpg-error-while-updating
