### ISSUE TITLE
Option to invite new participants to a spreed call

### ISSUE THREAD

**Issue by jasperla** [spreedbox/spreedbox#3]
On spreed.me one has the option to invite/add new participants to a call that's already ongoing. However it seems this feature is missing from the spreedme app on the spreedbox, is that correct? If so, is that intentional and/or will it be addressed in a future update?

**Comment by leonklingele** [comment]
This should work on the Spreedbox as well.

**Comment by jasperla** [comment]
I no longer have access to the Spreedbox. But if you say it works too (now?), let's close this ticket then.
