### ISSUE TITLE
Invitation username and password does not work 

### ISSUE THREAD

**Issue by reinerj** [spreedbox/spreedbox#6]
When you generate a temporary password, the user cannot login with the username and password to spreedbox. The login with the link does work correctly.

**Comment by fancycode** [comment]
@leonklingele: could you please check this? Seems to be related to https://github.com/strukturag/owncloud-spreedme

**Comment by leonklingele** [comment]
The TP can only be used to log in to spreed-webrtc.
@reinerj Were you trying to use it to log in to ownCloud? This of course will not work.

**Comment by reinerj** [comment]
OK, got it. This work then with the web-rtc login. But there is another small issue. You can not cancel in the login window.You have to close the browser window.

**Comment by strukturag-service** [comment]
This is the intended behavior:
You have to log in (either via ownCloud or Temporary Password) to use the Spreed service.

**Comment by reinerj** [comment]
Hi, but the cancel in the password window should work? Otherwise the button cancel button is more or less useless

**Comment by leonklingele** [comment]
Button removed with https://github.com/strukturag/owncloud-spreedme/commit/e8150be5ffbaf32103bf208356b9f6d1a843b1ce
A new release is coming soon. Thanks for your feedback @reinerj
