### ISSUE TITLE
Guest users are logged out when click on Dateien or Aktivität

### ISSUE THREAD

**Issue by reinerj** [spreedbox/spreedbox#7]
When a guest user login to Spreedbox (with the shared URL as example) he have the option to see the Dateien or Aktivität. When he click on this icons he get logged out. The question here is why he can see this options as he cannot use them. Should this not be hidden for him. And when he click on them he should not be logged out.

**Comment by fancycode** [comment]
@leonklingele: could please check how to disable the OC menu from https://github.com/strukturag/owncloud-spreedme for guest users?

**Comment by leonklingele** [comment]
Fixed via https://github.com/strukturag/owncloud-spreedme/commit/48004d2e3fa645d4dbaf2cb472218d34c1a5678d
