### ISSUE TITLE
Box does not boot (cannot find root filesystem)

### ISSUE THREAD

**Issue by steinhobelgruen** [spreedbox/spreedbox#8]
I tried Firmware release images 20160401 and 20160411, but boot always fails with the same error message (on HDMI console):

/dev/disk/by-label/spreedbox-rootfs does not exist

Images were installed to a 64GB Samsung micro SDXC card "EVO UHS-1" using dd on a Mac.
Did I miss something in the installation process?

**Comment by longsleep** [comment]
Hi,

the most likely reason for this error is that the SD card cannot be initialized by the Linux Kernel. You can try to change the settings in boot.ini (found on the first partition) and enable UHS by commenting the setenv disableuhs "disableuhs" line (put a hash # in front of it).

To do this insert the SD card into a card reader of your PC/MAC. The first partition is using Windows VFAT format and can be mounted pretty much on all operating systems by default.

Best regards
Simon

**Comment by steinhobelgruen** [comment]
That fixed it. Thanks a lot.
