### ISSUE TITLE
Unable to communicate via webrtc after latest update

### ISSUE THREAD

**Issue by jasperla** [spreedbox/spreedbox#9]
After applying the latest updates we're now unable to communicate with multiple browsers. Users can see their own microphone indicator bar expanding and contracting as they speak, but they cannot hear the other party. Or any variation of being unable to hear/speak to others.
Tested were firefox 45 and chrome 49. This seems to be on 0.25.4.

**Comment by longsleep** [comment]
Hi,
it seems unlikely that this issue is related to the updated Spreed WebRTC. I am not able to reproduce - what about camera, does that work / is the problem the audio only?

Thanks
Simon

**Comment by longsleep** [comment]
Tried to reproduce but works fine here between FF45 and Chrome 49.

**Comment by jasperla** [comment]
Thanks, then we'll have to figure out what's wrong at our end then.

**Comment by reinerj** [comment]
On our spreedbox we tried it with Laptops with Windows with FF and Chrome and with Mac with Iridium and FF and it does not work at all. It works again spreed.me but not with the spreedbox

**Comment by longsleep** [comment]
@reinerj What exactly does not work? Audio similar to what @jasperla did report?  What about video? Did it work before / stopped working after updating?

Please check the logs of the webrtc server at /var/log/spreed/webrtc/server.log and the browsers javascript developer console for errors. If you cannot establish a call at all please also check chrome://webrtc-internals/ (Chrome/Iridium) or about:webrtc (Firefox).

**Comment by reinerj** [comment]
Audio did not work. We did not try video. Id did working for us before the update. I dont see anything in the server logs. I enabled the log in Iridium and it created 2 binary files. What should be done with this files?

**Comment by longsleep** [comment]
Mhm, what is your exact setup? Both parties do not have a camera connected? The binary logs are not usefull at the moment. Check the entries like https://spreedbox/webrtc/ [6663-1] in chrome://webrtc-internals, click on one and then check the Conn-audio-1-0 line, and the ssrc_*_send and _recv parts as well. The more you paste here of that information the better we might understand what is going on. You can also download a text dump of each session by clicking the button on the top there. Paste the text data to https://paste.ubuntu.com/ or similar and share the link here. If you wish this data to stay private, you can send us by email to support@spreed.com.
